easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        # List the entity class name you want to manage
        Customer:
            class: App\Entity\User
            label: Utilisateur
            list:
                fields:
                    - property: firstName
                      label: Prénom
                    - property: lastName
                      label: Nom
                    - property: email
                      label: Email
                    - property: birthdate
                      label: Date de naissance
                      type: date
                    - property: roles
                      label: Roles
                actions:
                    - {name: 'addFidelity', type: 'route'}
            form:
                label: Utilisateur
                form_options: { validation_groups: [] }
                fields:
                    - property: firstName
                      label: Prénom
                    - property: lastName
                      label: Nom
                    - property: email
                      label: Email
                    - property: birthdate
                      label: Date de naissance
                    - property: enabled
                      label: Compte activé
                    - property: birthdate
                      type: date
                      label: Date de naissance
                      type_options:
                        widget: single_text
                    - property: created_at
                      type: date
                      label: Date de création
                      type_options:
                        disabled: true
                        widget: single_text
                    - property: password
                      css_class: 'd-none'
                      type: text
                      type_options:
                        mapped: false
                        disabled: true
                    - property: 'roles' 
                      type: 'choice'
                      type_options:
                        mapped: true
                        expanded: true
                        multiple: true
                        choices: { 'Caissière': 'ROLE_CASHIER', 'Client': 'ROLE_USER', 'Administeur': 'ROLE_ADMIN' }
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'

        Order:
            class: App\Entity\Card
            label: Carte
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'

        Product:
            class: App\Entity\Event
            label: Event
            edit:
                item_permission: 'ROLE_ADMIN'
            new:
                item_permission: 'ROLE_ADMIN'
            delete:
                item_permission: 'ROLE_ADMIN'
            list:
                fields:
                    - property: title
                      label: Titre
                    - property: multiplicator
                      label: Multiplieur
                    - property: start_event
                      label: Date de début
                      type: date
                    - property: end_event
                      label: Date de fin
                      type: date
            form:
                label: Event
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: multiplicator
                      label: Multiplieur
                    - property: start_event
                      type: date
                      label: Date de début
                      type_options:
                        widget: single_text
                    - property: end_event
                      type: date
                      label: Date de fin
                      type_options:
                        widget: single_text
        Orders:     
            class: App\Entity\Gift
            label: Cadeaux
            list:
                fields:
                    - property: title
                      label: Titre
                    - property: nb_fidelity
                      label: Points de fidélité
                    - property: picture
                      label: Image
                      type: image
                      base_path: '/gifts/'
            form:
                item_permission: 'ROLE_ADMIN'
                label: Cadeaux
                form_options: { validation_groups: [] }
                fields:
                    - property: title
                      label: Titre
                    - property: nb_fidelity
                      label: Points de fidélité
                    - property: picture
                      label: Image
                      type: file_upload
                      type_options:
                          upload_dir: public/gifts/
            delete:
                item_permission: 'ROLE_ADMIN'


    site_name: 'Cinesuper'
    design:
        brand_color: '#e67e22'
        menu:
            - { entity: 'Customer', icon: 'user' }
            - { entity: 'Order', icon: 'id-card' }
            - { entity: 'Product', icon: 'calendar-alt' }
            - { entity: 'Orders', icon: 'gift' }